/**
 * PROJECT FTTH ENTERPRISE DASHBOARD - INITIAL SAMPLE DATASET
 * Pre-loaded FTTH FAT Port dataset strictly following the exact user column specification:
 * No, City, Area, FAT, Tikor FAT, Date RFS, Years, MITRA, Action, IDDLE, USED, TOTAL
 */

const FTTH_SAMPLE_DATASET = [
  {
    No: 1,
    City: "Jakarta Selatan",
    Area: "Kebayoran Baru",
    FAT: "FAT-JKS-001",
    "Tikor FAT": "-6.2442, 106.8006",
    "Date RFS": "2026-07-01",
    Years: 2026,
    MITRA: "PT Telecom Infrastructure",
    Action: "RFS Completed",
    IDDLE: 3,
    USED: 13,
    TOTAL: 16,
    // Calculated compatibility helpers
    Date: "2026-07-01",
    Region: "Jakarta Selatan",
    Cluster: "Kebayoran Baru (FAT-JKS-001)",
    Site: "FAT-JKS-001",
    POP: "POP-JKS-MAIN",
    ODC: "ODC-JKS-01",
    ODP: "FAT-JKS-001",
    Vendor: "PT Telecom Infrastructure",
    Supervisor: "Budi Santoso",
    PIC: "Andi Wijaya",
    Status: "Completed",
    TargetHP: 16,
    ActualHP: 13,
    Lat: -6.2442,
    Lng: 106.8006
  },
  {
    No: 2,
    City: "Jakarta Selatan",
    Area: "Pondok Indah",
    FAT: "FAT-JKS-002",
    "Tikor FAT": "-6.2653, 106.7842",
    "Date RFS": "2026-07-03",
    Years: 2026,
    MITRA: "PT Telecom Infrastructure",
    Action: "In Progress",
    IDDLE: 6,
    USED: 10,
    TOTAL: 16,
    Date: "2026-07-03",
    Region: "Jakarta Selatan",
    Cluster: "Pondok Indah (FAT-JKS-002)",
    Site: "FAT-JKS-002",
    POP: "POP-JKS-MAIN",
    ODC: "ODC-JKS-02",
    ODP: "FAT-JKS-002",
    Vendor: "PT Telecom Infrastructure",
    Supervisor: "Budi Santoso",
    PIC: "Rizky Pratama",
    Status: "In Progress",
    TargetHP: 16,
    ActualHP: 10,
    Lat: -6.2653,
    Lng: 106.7842
  },
  {
    No: 3,
    City: "Jakarta Barat",
    Area: "Puri Indah",
    FAT: "FAT-JKB-001",
    "Tikor FAT": "-6.1864, 106.7345",
    "Date RFS": "2026-07-05",
    Years: 2026,
    MITRA: "PT Optik Nusantara",
    Action: "RFS Completed",
    IDDLE: 1,
    USED: 15,
    TOTAL: 16,
    Date: "2026-07-05",
    Region: "Jakarta Barat",
    Cluster: "Puri Indah (FAT-JKB-001)",
    Site: "FAT-JKB-001",
    POP: "POP-JKB-01",
    ODC: "ODC-JKB-01",
    ODP: "FAT-JKB-001",
    Vendor: "PT Optik Nusantara",
    Supervisor: "Hendra Wijaya",
    PIC: "Dewi Lestari",
    Status: "Completed",
    TargetHP: 16,
    ActualHP: 15,
    Lat: -6.1864,
    Lng: 106.7345
  },
  {
    No: 4,
    City: "Bandung",
    Area: "Dago",
    FAT: "FAT-BDG-001",
    "Tikor FAT": "-6.8841, 107.6136",
    "Date RFS": "2026-07-08",
    Years: 2026,
    MITRA: "PT Fiber Karya",
    Action: "RFS Completed",
    IDDLE: 2,
    USED: 14,
    TOTAL: 16,
    Date: "2026-07-08",
    Region: "Bandung",
    Cluster: "Dago (FAT-BDG-001)",
    Site: "FAT-BDG-01",
    POP: "POP-BDG-NORTH",
    ODC: "ODC-BDG-01",
    ODP: "FAT-BDG-001",
    Vendor: "PT Fiber Karya",
    Supervisor: "Agus Pratama",
    PIC: "Fajar Nugraha",
    Status: "Completed",
    TargetHP: 16,
    ActualHP: 14,
    Lat: -6.8841,
    Lng: 107.6136
  },
  {
    No: 5,
    City: "Bandung",
    Area: "Buah Batu",
    FAT: "FAT-BDG-002",
    "Tikor FAT": "-6.9532, 107.6321",
    "Date RFS": "2026-07-10",
    Years: 2026,
    MITRA: "PT Fiber Karya",
    Action: "In Progress",
    IDDLE: 8,
    USED: 8,
    TOTAL: 16,
    Date: "2026-07-10",
    Region: "Bandung",
    Cluster: "Buah Batu (FAT-BDG-002)",
    Site: "FAT-BDG-02",
    POP: "POP-BDG-SOUTH",
    ODC: "ODC-BDG-02",
    ODP: "FAT-BDG-002",
    Vendor: "PT Fiber Karya",
    Supervisor: "Agus Pratama",
    PIC: "Eko Prasetyo",
    Status: "In Progress",
    TargetHP: 16,
    ActualHP: 8,
    Lat: -6.9532,
    Lng: 107.6321
  },
  {
    No: 6,
    City: "Surabaya",
    Area: "Gubeng",
    FAT: "FAT-SBY-001",
    "Tikor FAT": "-7.2754, 112.7541",
    "Date RFS": "2026-07-12",
    Years: 2026,
    MITRA: "PT Jaringan Utama",
    Action: "RFS Completed",
    IDDLE: 0,
    USED: 16,
    TOTAL: 16,
    Date: "2026-07-12",
    Region: "Surabaya",
    Cluster: "Gubeng (FAT-SBY-001)",
    Site: "FAT-SBY-01",
    POP: "POP-SBY-MAIN",
    ODC: "ODC-SBY-01",
    ODP: "FAT-SBY-001",
    Vendor: "PT Jaringan Utama",
    Supervisor: "Siti Rahmawati",
    PIC: "Dedi Kurniawan",
    Status: "Completed",
    TargetHP: 16,
    ActualHP: 16,
    Lat: -7.2754,
    Lng: 112.7541
  },
  {
    No: 7,
    City: "Surabaya",
    Area: "Rungkut",
    FAT: "FAT-SBY-002",
    "Tikor FAT": "-7.3211, 112.7788",
    "Date RFS": "2026-07-15",
    Years: 2026,
    MITRA: "PT Jaringan Utama",
    Action: "Pending ROW",
    IDDLE: 12,
    USED: 4,
    TOTAL: 16,
    Date: "2026-07-15",
    Region: "Surabaya",
    Cluster: "Rungkut (FAT-SBY-002)",
    Site: "FAT-SBY-02",
    POP: "POP-SBY-MAIN",
    ODC: "ODC-SBY-02",
    ODP: "FAT-SBY-002",
    Vendor: "PT Jaringan Utama",
    Supervisor: "Siti Rahmawati",
    PIC: "Rina Gunawan",
    Status: "Delayed",
    TargetHP: 16,
    ActualHP: 4,
    Lat: -7.3211,
    Lng: 112.7788
  },
  {
    No: 8,
    City: "Medan",
    Area: "Medan Baru",
    FAT: "FAT-MDN-001",
    "Tikor FAT": "3.5781, 98.6653",
    "Date RFS": "2026-07-17",
    Years: 2026,
    MITRA: "PT Optik Nusantara",
    Action: "In Progress",
    IDDLE: 5,
    USED: 11,
    TOTAL: 16,
    Date: "2026-07-17",
    Region: "Medan",
    Cluster: "Medan Baru (FAT-MDN-001)",
    Site: "FAT-MDN-01",
    POP: "POP-MDN-01",
    ODC: "ODC-MDN-01",
    ODP: "FAT-MDN-001",
    Vendor: "PT Optik Nusantara",
    Supervisor: "Hendra Wijaya",
    PIC: "Bambang Sukoco",
    Status: "In Progress",
    TargetHP: 16,
    ActualHP: 11,
    Lat: 3.5781,
    Lng: 98.6653
  },
  {
    No: 9,
    City: "Semarang",
    Area: "Candi",
    FAT: "FAT-SMG-001",
    "Tikor FAT": "-7.0051, 110.4229",
    "Date RFS": "2026-07-19",
    Years: 2026,
    MITRA: "PT Telecom Infrastructure",
    Action: "Pending",
    IDDLE: 14,
    USED: 2,
    TOTAL: 16,
    Date: "2026-07-19",
    Region: "Semarang",
    Cluster: "Candi (FAT-SMG-001)",
    Site: "FAT-SMG-01",
    POP: "POP-SMG-01",
    ODC: "ODC-SMG-01",
    ODP: "FAT-SMG-001",
    Vendor: "PT Telecom Infrastructure",
    Supervisor: "Budi Santoso",
    PIC: "Irwan Setiawan",
    Status: "Pending",
    TargetHP: 16,
    ActualHP: 2,
    Lat: -7.0051,
    Lng: 110.4229
  },
  {
    No: 10,
    City: "Jakarta Timur",
    Area: "Rawamangun",
    FAT: "FAT-JKT-001",
    "Tikor FAT": "-6.1953, 106.8834",
    "Date RFS": "2026-07-21",
    Years: 2026,
    MITRA: "PT Fiber Karya",
    Action: "RFS Completed",
    IDDLE: 1,
    USED: 15,
    TOTAL: 16,
    Date: "2026-07-21",
    Region: "Jakarta Timur",
    Cluster: "Rawamangun (FAT-JKT-001)",
    Site: "FAT-JKT-01",
    POP: "POP-JKT-EAST",
    ODC: "ODC-JKT-01",
    ODP: "FAT-JKT-001",
    Vendor: "PT Fiber Karya",
    Supervisor: "Agus Pratama",
    PIC: "Maya Sari",
    Status: "Completed",
    TargetHP: 16,
    ActualHP: 15,
    Lat: -6.1953,
    Lng: 106.8834
  }
];

const FTTH_SAMPLE_ISSUES = [
  {
    IssueID: "ISS-2026-001",
    Date: "2026-07-14",
    Area: "Surabaya",
    Cluster: "FAT-SBY-002 (Rungkut)",
    Issue: "Izin ROW (Right of Way) dari Pemda belum keluar untuk penanaman tiang FAT.",
    Severity: "Critical",
    PIC: "Rina Gunawan",
    Vendor: "PT Jaringan Utama",
    Status: "Open",
    Progress: "30%",
    Photo: "assets/images/sample_issue_1.jpg"
  },
  {
    IssueID: "ISS-2026-002",
    Date: "2026-07-16",
    Area: "Bandung",
    Cluster: "FAT-BDG-002 (Buah Batu)",
    Issue: "Kabel feeder drop terputus akibat galian drainase kota.",
    Severity: "High",
    PIC: "Eko Prasetyo",
    Vendor: "PT Fiber Karya",
    Status: "In Progress",
    Progress: "70%",
    Photo: "assets/images/sample_issue_2.jpg"
  },
  {
    IssueID: "ISS-2026-003",
    Date: "2026-07-18",
    Area: "Semarang",
    Cluster: "FAT-SMG-001 (Candi)",
    Issue: "Kapasitas port FAT penuh, perlu penambahan splitter.",
    Severity: "Medium",
    PIC: "Irwan Setiawan",
    Vendor: "PT Telecom Infrastructure",
    Status: "Open",
    Progress: "40%",
    Photo: "assets/images/sample_issue_3.jpg"
  }
];
